# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/motorola/addison/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/motorola/addison/proprietary/bin/motosh:system/bin/motosh \
    vendor/motorola/addison/proprietary/etc/acdbdata/Bluetooth_cal.acdb:system/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/addison/proprietary/etc/acdbdata/General_cal.acdb:system/etc/acdbdata/General_cal.acdb \
    vendor/motorola/addison/proprietary/etc/acdbdata/Global_cal.acdb:system/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/addison/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/addison/proprietary/etc/acdbdata/Hdmi_cal.acdb:system/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/addison/proprietary/etc/acdbdata/Headset_cal.acdb:system/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/addison/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/addison/proprietary/etc/firmware/marley-dsp1-ultrasound.wmfw:system/etc/firmware/marley-dsp1-ultrasound.wmfw \
    vendor/motorola/addison/proprietary/etc/firmware/marley-dsp2-aov-frontend.wmfw:system/etc/firmware/marley-dsp2-aov-frontend.wmfw \
    vendor/motorola/addison/proprietary/etc/firmware/marley-dsp3-aov-control.wmfw:system/etc/firmware/marley-dsp3-aov-control.wmfw \
    vendor/motorola/addison/proprietary/etc/firmware/sensorhubfw.bin:system/etc/firmware/sensorhubfw.bin \
    vendor/motorola/addison/proprietary/etc/firmware/synaptics-s3508-16082601-255c40-addison.tdat:system/etc/firmware/synaptics-s3508-16082601-255c40-addison.tdat \
    vendor/motorola/addison/proprietary/etc/firmware/synaptics-s3508sga-16082601-255c40-addison.tdat:system/etc/firmware/synaptics-s3508sga-16082601-255c40-addison.tdat \
    vendor/motorola/addison/proprietary/lib/hw/camera.rc.so:system/lib/hw/camera.rc.so \
    vendor/motorola/addison/proprietary/lib/hw/camera.vendor.msm8953.so:system/lib/hw/camera.vendor.msm8953.so \
    vendor/motorola/addison/proprietary/lib/hw/sensorhub.msm8953.so:system/lib/hw/sensorhub.msm8953.so \
    vendor/motorola/addison/proprietary/lib/hw/sensors.addison.so:system/lib/hw/sensors.addison.so \
    vendor/motorola/addison/proprietary/lib/hw/sensors.iio.so:system/lib/hw/sensors.iio.so \
    vendor/motorola/addison/proprietary/lib/hw/sensors.msm8953.so:system/lib/hw/sensors.msm8953.so \
    vendor/motorola/addison/proprietary/lib/lib_mottof.so:system/lib/lib_mottof.so \
    vendor/motorola/addison/proprietary/lib/libadvalgcore.so:system/lib/libadvalgcore.so \
    vendor/motorola/addison/proprietary/lib/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so \
    vendor/motorola/addison/proprietary/lib/libcamerabgprocservice.so:system/lib/libcamerabgprocservice.so \
    vendor/motorola/addison/proprietary/lib/libfamily_photo.so:system/lib/libfamily_photo.so \
    vendor/motorola/addison/proprietary/lib/libiio.so:system/lib/libiio.so \
    vendor/motorola/addison/proprietary/lib/libjscore.so:system/lib/libjscore.so \
    vendor/motorola/addison/proprietary/lib/libjustshoot.so:system/lib/libjustshoot.so \
    vendor/motorola/addison/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/motorola/addison/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/motorola/addison/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/motorola/addison/proprietary/lib/libmorpho_image_stabilizer4.so:system/lib/libmorpho_image_stabilizer4.so \
    vendor/motorola/addison/proprietary/lib/libmot-qc-fd-offline.so:system/lib/libmot-qc-fd-offline.so \
    vendor/motorola/addison/proprietary/lib/libmot_afd.so:system/lib/libmot_afd.so \
    vendor/motorola/addison/proprietary/lib/libmot_lux_standardization.so:system/lib/libmot_lux_standardization.so \
    vendor/motorola/addison/proprietary/lib/libmotimager_utils.so:system/lib/libmotimager_utils.so \
    vendor/motorola/addison/proprietary/lib/libsensorhub.so:system/lib/libsensorhub.so \
    vendor/motorola/addison/proprietary/vendor/lib/libactuator_mot_lc898212xd.so:system/vendor/lib/libactuator_mot_lc898212xd.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_4k_ihdr_video_3a.so:system/vendor/lib/libchromatix_ov16860_4k_ihdr_video_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_4k_video_3a.so:system/vendor/lib/libchromatix_ov16860_4k_video_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_common.so:system/vendor/lib/libchromatix_ov16860_common.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_hfr_120.so:system/vendor/lib/libchromatix_ov16860_cpp_hfr_120.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_ihdr_video.so:system/vendor/lib/libchromatix_ov16860_cpp_ihdr_video.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_ihdr_video_4k.so:system/vendor/lib/libchromatix_ov16860_cpp_ihdr_video_4k.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_liveshot.so:system/vendor/lib/libchromatix_ov16860_cpp_liveshot.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_liveshot_4k.so:system/vendor/lib/libchromatix_ov16860_cpp_liveshot_4k.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_liveshot_4k_ihdr.so:system/vendor/lib/libchromatix_ov16860_cpp_liveshot_4k_ihdr.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_liveshot_ihdr.so:system/vendor/lib/libchromatix_ov16860_cpp_liveshot_ihdr.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_snapshot.so:system/vendor/lib/libchromatix_ov16860_cpp_snapshot.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_video.so:system/vendor/lib/libchromatix_ov16860_cpp_video.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_cpp_video_4k.so:system/vendor/lib/libchromatix_ov16860_cpp_video_4k.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_default_ihdr_video.so:system/vendor/lib/libchromatix_ov16860_default_ihdr_video.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_default_video.so:system/vendor/lib/libchromatix_ov16860_default_video.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_hfr_120.so:system/vendor/lib/libchromatix_ov16860_hfr_120.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_hfr_120_3a.so:system/vendor/lib/libchromatix_ov16860_hfr_120_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_ihdr_video_3a.so:system/vendor/lib/libchromatix_ov16860_ihdr_video_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_ihdr_video_4k.so:system/vendor/lib/libchromatix_ov16860_ihdr_video_4k.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_postproc.so:system/vendor/lib/libchromatix_ov16860_postproc.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_snapshot.so:system/vendor/lib/libchromatix_ov16860_snapshot.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_video_4k.so:system/vendor/lib/libchromatix_ov16860_video_4k.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_zsl_preview_3a.so:system/vendor/lib/libchromatix_ov16860_zsl_preview_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov16860_zsl_video_3a.so:system/vendor/lib/libchromatix_ov16860_zsl_video_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_common.so:system/vendor/lib/libchromatix_ov5693_common.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_cpp_hfr_120.so:system/vendor/lib/libchromatix_ov5693_cpp_hfr_120.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_cpp_liveshot.so:system/vendor/lib/libchromatix_ov5693_cpp_liveshot.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_cpp_snapshot.so:system/vendor/lib/libchromatix_ov5693_cpp_snapshot.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_cpp_video.so:system/vendor/lib/libchromatix_ov5693_cpp_video.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_default_video.so:system/vendor/lib/libchromatix_ov5693_default_video.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_default_video_3a.so:system/vendor/lib/libchromatix_ov5693_default_video_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_hfr_120.so:system/vendor/lib/libchromatix_ov5693_hfr_120.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_hfr_120_3a.so:system/vendor/lib/libchromatix_ov5693_hfr_120_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_postproc.so:system/vendor/lib/libchromatix_ov5693_postproc.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_snapshot.so:system/vendor/lib/libchromatix_ov5693_snapshot.so \
    vendor/motorola/addison/proprietary/vendor/lib/libchromatix_ov5693_snapshot_3a.so:system/vendor/lib/libchromatix_ov5693_snapshot_3a.so \
    vendor/motorola/addison/proprietary/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    vendor/motorola/addison/proprietary/vendor/lib/libflash_sky81298.so:system/vendor/lib/libflash_sky81298.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_dcrf.so:system/vendor/lib/libmmcamera2_dcrf.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_mct.so:system/vendor/lib/libmmcamera2_mct.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_cac3_lib.so:system/vendor/lib/libmmcamera_cac3_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_dbg.so:system/vendor/lib/libmmcamera_dbg.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_dcrf_lib.so:system/vendor/lib/libmmcamera_dcrf_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_dummyalgo.so:system/vendor/lib/libmmcamera_dummyalgo.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_eebinparse.so:system/vendor/lib/libmmcamera_eebinparse.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_facedetection_lib.so:system/vendor/lib/libmmcamera_facedetection_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_abf40.so:system/vendor/lib/libmmcamera_isp_abf40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_bcc40.so:system/vendor/lib/libmmcamera_isp_bcc40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so:system/vendor/lib/libmmcamera_isp_bf_stats47.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_bpc40.so:system/vendor/lib/libmmcamera_isp_bpc40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_demosaic40.so:system/vendor/lib/libmmcamera_isp_demosaic40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_gamma40.so:system/vendor/lib/libmmcamera_isp_gamma40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff40.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder44.so:system/vendor/lib/libmmcamera_isp_scaler_encoder44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_template.so:system/vendor/lib/libmmcamera_isp_template.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_llvd.so:system/vendor/lib/libmmcamera_llvd.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ov16860.so:system/vendor/lib/libmmcamera_ov16860.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ov16860_eeprom.so:system/vendor/lib/libmmcamera_ov16860_eeprom.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ov16860_pdaf.so:system/vendor/lib/libmmcamera_ov16860_pdaf.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ov5693.so:system/vendor/lib/libmmcamera_ov5693.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ov5693_eeprom.so:system/vendor/lib/libmmcamera_ov5693_eeprom.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ovpdaf.so:system/vendor/lib/libmmcamera_ovpdaf.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_paaf_lib.so:system/vendor/lib/libmmcamera_paaf_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ppeiscore.so:system/vendor/lib/libmmcamera_ppeiscore.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_stillmore_lib.so:system/vendor/lib/libmmcamera_stillmore_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_sw2d_lib.so:system/vendor/lib/libmmcamera_sw2d_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_thread_services.so:system/vendor/lib/libmmcamera_thread_services.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_trueportrait_lib.so:system/vendor/lib/libmmcamera_trueportrait_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmcamera_vstab_module.so:system/vendor/lib/libmmcamera_vstab_module.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    vendor/motorola/addison/proprietary/vendor/lib/libmotocalibration.so:system/vendor/lib/libmotocalibration.so \
    vendor/motorola/addison/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/motorola/addison/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/motorola/addison/proprietary/vendor/lib/libsensorhubservice_jni.so:system/vendor/lib/libsensorhubservice_jni.so
